# -*- coding: utf-8 -*-
"""practice day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Tqzeo4GoCIvh6L_lxDJgEc3prtn93Nu
"""

# nested if-else
# x=10
# x>5
x=10
if x>5:
  print("value greater than 5")
  if(x>20):
    print("value greater than 20")
  else:
    print("value less than 5")

#take integer value from user age and city
age=int(input())
if age>18:
  print("adult")
  city=input()
  if city=='jaipur':
    print("adult and belogs to jaipur")
  else:
    print("adult but doesn't belongs to jaipur")

num=int(input())
if num%2!=0:
  print("odd number")
  if num%5==0 and num%11==0:
    print("number is odd and divisble by 5 and 11")
  else:
    print("number is odd but not divisble by 5 and 11")

#basic loops
# for, while
#for=> no of iterations decided
# for variable in range(start,end,[step=1])
# 4 is excluded
for i in range(10,16):
  print("hello")

for i in range(16,10,-2):
  print("hello")

sum=0
for i in range(2,9):
 sum+=i
 print(sum)

product=1
for i in range(80,50,-1):
  product*=i
print(product)

for i in range(2,21):
  if i%2==0:
    print(f'even no is {i}')
  else:
    print(f'odd no is {i}')

sum=0
sum1=0
for i in range(2,21):
  if i%2==0:
    sum+=i
    print(sum)
  else:
    sum1+=i
    print(sum)

#for fixed
#while -not fixed(if variable is affected)-loop to be affected
x=2
while (x<10):
  print(x)
  x+=1

x=2
while (x>0):
  print(x)
  x-=1

#sum of no b/w 10 to 18
num=10
sum=0
while num<18:
  sum+=num
  num+=1
print(sum)

#starting 15 no divisble by 6
num=1
while num>:

#difference b/w python2 and python 3?
#call by  value and call by reference
#
#what is namespace in python?
#what is the difference b/w is and == operator?
#what are lifescope of a variable?

def find_unique(arr):
    unique = 0
    for num in arr:
        unique ^= num  # Apply XOR to all elements
    return unique

arr = [4, 3, 2, 4, 1, 2, 1]
print(find_unique(arr))  # Output: 3